baseURL = 'https://jorgenhanisch.github.io/mitt-nettsted/'
locale = 'en-us'
title = 'My New Hugo Project'
[[menus.main]]
name = "Arbeider"
url = "/arbeider/"
weight = 1

[[menus.main]]
name = "Kompetanse"
url = "/kompetanse/"
weight = 2

[[menus.main]]
name = "Kontakt"
url = "/kontakt/"
weight = 3